<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>3145d22f-1b2e-4d5c-9b75-7c69c17c2fd2</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<Content Remove="appsettings.Development-Encrypted.json" />
		<Content Remove="appsettings.Development.json" />
		<Content Remove="appsettings.Production_Encrypted.json" />
	</ItemGroup>

	<ItemGroup>
		<None Include="appsettings.Development-Encrypted.json" >
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>

		<None Include="appsettings.Development.json">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>
		<None Include="appsettings.Production_Encrypted.json" >
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Google.Apis.Auth" Version="1.74.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.*" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.*" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.1.0" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.14" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.*">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.*" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.*">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<!--<PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />-->
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.2" />
	</ItemGroup>

</Project>
